### ISSUE TITLE
HWBUG does not run properly on 02F26L

### ISSUE THREAD

**Issue by dpfeuffer** [MEN-Mikro-Elektronik/hwbug#1]
Hardware: F26L + 02F215-
Operating System: "Ubuntu 18.04.2 LTS" 4.18.0-20-generic 
HWBUG from jpe-dev branch, 4fc31b1e92357115a53bb1ce5eda5f5808084f47

- compiled hwbug using make
- fpga_load_x86-32 -s shows the FPGA on 02F125-:
  40  14  14   0  0x1a88   0x4d45    0x00e5
- Reading the chameleon table provides the FPGA configuration:
```
fpga_load_x86-32 1a88 4d45 e5 0 -t
...
Idx DevId  Module                   Grp Inst Var Rev IRQ BAR Offset     Address
--- ------ ------------------------ --- ---- --- --- --- --- ---------- ----------
  0 0x0018 16Z024_SRAM                0    0   1  17  63   0 0x00000000 0x81500000
```

- Try to read mem at addr 81500000 doesn't work:
HwBug> CB 81500000
00000000: f3 -> 
00000001: ee -> 
00000002: 00 ->
There must be the magic id of the chameleon table: 0x4101 

- Using the busybox tool /bin/busybox devmem 0x8150000 16
The return value is 0x4101 (which is the expected value!)

If you have further questions: The problem was discovered from a colleague. But we are now both on holiday till 24.6.

**Comment by KonradJPE** [comment]
It should be working now. I am now able to correctly read magic id of the chameleon table.

I have tested configuration:
F26L+F215 on Ubuntu 18.04.2 LTS 4.15.0-46-generic.
