### ISSUE TITLE
64-bit compliant version of hwbug found

### ISSUE THREAD

**Issue by dpfeuffer** [MEN-Mikro-Elektronik/hwbug#3]
[hwbug.zip](https://github.com/MEN-Mikro-Elektronik/hwbug/files/3368925/hwbug.zip)
Attached is a git repo with a hwbug that works on F23P 64-bit (see #2).

Could you please compare the sources and update the hwbug at github.
Maybe outdated hwbug sources were provided to you/github. Sorry for that.
It seems to me that the attached sources are the latest one from MEN (reworked from a colleague who quit the job).

Additional request: Please check if it is possible to specify 64-bit addresses at the hwbug command interface. If not, please extend it.

**Comment by dpfeuffer** [comment]
Please use the hwbug.zip/SRC/linux sources as reference to fix #2.
Please enhance the README.md file with the explanations/examples from the hwbug.zip/README.

**Comment by KonradJPE** [comment]
> Additional request: Please check if it is possible to specify 64-bit addresses at the hwbug command interface. If not, please extend it.

Do you mean for hwbug_cmd, or for both tools (hwbug_cmd and hwbug)?

Im not sure in which cases such 64bit address could be used. It seems to me that all attached PCI devices are mapped into 32bit address.  What data beyond 32bit address space would you like to read with this tools?
For instance to be able to read system RAM data (which address can be mapped beyond 32bit) Linux kernel should be compiled with  CONFIG_STRICT_DEVMEM=n, otherwise this operations is not permitted.

**Comment by dpfeuffer** [comment]
>Do you mean for hwbug_cmd, or for both tools (hwbug_cmd and hwbug)?

Could be useful for both.

>Im not sure in which cases such 64bit address could be used. It seems to me that all attached PCI devices are mapped into 32bit address. What data beyond 32bit address space would you like to read with this tools?

PCI(e) devices can also use 64-bit physical addresses by combining two 32-bit BARs for one 64-bit address. Ok, I think we have currently no MEN HW that uses this.
I thought about my request to support 64-bit addresses and because until now I never missed this feature and because of your hint about CONFIG_STRICT_DEVMEM, I change my request:
"Please check if it is possible to specify 64-bit addresses at the hwbug command interface. If not, add a note, that currently only 32-bit addresses are supported."
We will do 64-bit address support if we need it and have HW to test it.

**Comment by KonradJPE** [comment]
> "Please check if it is possible to specify 64-bit addresses at the hwbug command interface. If not, add a note, that currently only 32-bit addresses are supported."

Note: "Only 32-bit addresses are supported" added.
